### ISSUE TITLE
User Story 13, User can log out

### ISSUE THREAD

**Issue by iandouglas** [Mycobee/little-shop-4#66]
```
As a registered user, merchant, or admin
When I visit the logout path
I am redirected to the welcome / home page of the site
And I see a flash message that indicates I am logged out
Any items I had in my shopping cart are deleted
```

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [ ] code is reviewed
- [ ] branch is merged
- [ ] all tests still pass

child of #70

child of #82

**Comment by Mycobee** [comment]
Can't stub login.  Must be done manually

**Comment by Mycobee** [comment]
@zachlp2016  this card should be easy to knock out too with cart functionality, all that is left is the cart deletion
